name: Lphy tests
on: [ push, pull_request, workflow_dispatch ]

jobs:
  test-lphy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 15
        uses: actions/setup-java@v1
        with:
          java-version: 15.0.1
      - name: Run Ant
        run: ant -noinput -buildfile build.xml github-actions